# tools/python_executor.py

import matplotlib.pyplot as plt
import traceback
from typing import Any, List, Dict
from agents.viz_agent import sanitize_plot_code

def run_plot_code(python_code: str, data: Any):
    """
    Execute matplotlib plotting code safely.

    Parameters:
    - python_code: Python code generated by viz_agent
    - data: SQL result (list of dicts / list of tuples)

    The plotting code MUST assume:
    - `data` variable already exists
    """
    # Sanitize the code to remove any imports
    python_code = sanitize_plot_code(python_code)
    
    # ---------------- SAFE EXECUTION CONTEXT ----------------
    safe_globals = {
        "__builtins__": __builtins__,
        "plt": plt,
        "data": data  # ← CRITICAL: Pass data here
    }

    try:
        fig = plt.gcf()        # get current figure
        exec(python_code, safe_globals)
        return fig


    except Exception as e:
        traceback.print_exc()
        raise RuntimeError(f"Plot execution failed: {e}")